version: "3.9"
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./prisma/database.sqlite:/usr/src/app/prisma/database.sqlite

